# Generated by Django 3.2.5 on 2023-04-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
